name: RoboArchitect Release

on: [push]

env:
  release: "2.0.1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download windows jre
        run: |
            wget -c https://cdn.azul.com/zulu/bin/zulu8.46.0.19-ca-jdk8.0.252-win_i686.zip -O jdk.zip
            unzip jdk.zip -d ./java
            mv ./java/*/* ./java
      - name: Build with Maven
        run: |
            echo "${{ secrets.RELEASE_KEYSTORE }}" > release.p12.asc
            echo "${{ secrets.RELEASE_KEYSTORE_PASS }}" | gpg --batch --no-tty --yes --passphrase-fd 0 --decrypt release.p12.asc > release.p12
            mvn -e clean package -P mac,windows,windows-with-jre,linux,sign,sign-exe -Drobo.version="${{ env.release }}" -Dkeystore.path="release.p12" -Dkeystore.type="pkcs12" -Dkeystore.alias="${{ secrets.RELEASE_ALIAS }}" -Dkeystore.store.password="${{ secrets.RELEASE_PASS }}" --file pom.xml
      - name: Release
        uses: xresloader/upload-to-github-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./target/RoboArchitectWindows/*.exe; ./target/Robo*.jar; ./target/linux/linuxRoboArchitect*.zip; ./target/windows/windowsRoboArchitect*.zip; ./target/mac/macRoboArchitect*.zip;"
          tags: true
          draft: false
          branches: "master"
          tag_name: "v${{ env.release }}"
          verbose: true
