name: RoboArchitect Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: |
                      ${{ runner.os }}-maven-
      - name: Build with Maven
        run: |
            echo "${{ secrets.RELEASE_KEYSTORE }}" > release.p12.asc
            echo "${{ secrets.RELEASE_KEYSTORE_PASS }}" | gpg --batch --no-tty --yes --passphrase-fd 0 --decrypt release.p12.asc > release.p12
            mvn -e clean package -P mac,windows,windows-with-jre,linux,sign,sign-exe -Dkeystore.path="release.p12" -Dkeystore.type="pkcs12" -Dkeystore.alias="${{ secrets.RELEASE_ALIAS }}" -Dkeystore.store.password="${{ secrets.RELEASE_PASS }}" --file pom.xml
      - name: Release
        uses: xresloader/upload-to-github-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./target/*.exe; ./target/Robo*.jar; ./target/linux/linuxRoboArchitect*.zip; ./target/mac/macRoboArchitect*.zip;"
          tags: true
          draft: true
          tag_name: "v1.2.8"
          verbose: true
