name: RoboArchitect Release

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -Pmac,linux,windows -B clean package --file pom.xml
      - name: Release
        uses: xresloader/upload-to-github-release@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "./target/*.exe; ./target/Robo*.jar; ./target/linux/RoboArchitect; /target/mac/RoboArchitect;"
          tags: true
          draft: false
          branches: "master"
          tag_name: "v1.2.6"
          verbose: true
